### ISSUE TITLE
Opam package is broken

### ISSUE THREAD

**Issue by Drup** [janestreet/ppx_core#1]
```
#require "ppx_core";;
module P = Ppx_core ;;
Error: Reference to undefined global `Ppx_core'
```

Same deal for compilation, obviously. I don't even understand how your other packages are compiling. :|

**Comment by diml** [comment]
It's related to janestreet/ppx_sexp_conv#1. Because ppx\_sexp\_conv and other deriving plugins depends on ppx\_core, ppx\_core must have a META that works well with ppx_deriving. That means that ppx\_core doesn't behave as a normal library by default...

It will be simpler when ppx\_deriving uses ocamlfind directly.

Currently one workaround is to do this:

```
#predicates "ppx_driver";;
#require "ppx_core";;
```

However that also means that packages like ppx\_sexp\_conv will behave as libraries...

```
#predicates "ppx_driver";;
#require "ppx_sexp_conv";;
# module P = Ppx_sexp_conv;;
module P = Ppx_sexp_conv
# type t = int [@@deriving sexp];;
Cannot locate deriver sexp
```

**Comment by Drup** [comment]
Couldn't you have two ocamlfind package, one deriving-like and one library-like ?

Also, what do I have to put in my `_tags` to make the whole working ?

**Comment by diml** [comment]
> Couldn't you have two ocamlfind packages, one deriving-like and one library-like ?

I'll try  to sort something out for the next release

> Also, what do I have to put in my _tags to make the whole thing working ?

If you mean "what is the equivalent of `#predicates "ppx_driver";;`", it is:

```
<**/*.ml{,i}>: predicate(ppx_driver)
```

**Comment by Drup** [comment]
Ok, thanks!

**Comment by Drup** [comment]
FYI, I forgot to answer but the right line is:
```
<*/*.{native,byte}>: predicate(ppx_driver)
```

This bug is horrible for newcomers, by the way. If you don't solve it, you should at least document it explicitly.

**Comment by diml** [comment]
Is the problem still present with the 113.24 release? I changed things so that ppx\_deriving plugins depends on `ppx_core.for-ppx-deriving`...

**Comment by mshinwell** [comment]
No comment back from the reporter, so assuming fixed.
