### ISSUE TITLE
Circular dependency?

### ISSUE THREAD

**Issue by jaapb** [janestreet/ppx_core#11]
Not sure this is the right place to report, but: 
I'm trying to update ppx_core to 0.9.0 in pkgsrc, and find the following dependency cycle:
ppx_core requires ocaml-compiler-libs.common, part of core;
core requires core_kernel;
core_kernel requires ppx_base;
ppx_base requires ppx_compare;
ppx_compare requires ppx_metaquot;
ppx_metaquot requires ppx_core (at least according to its opam file).

Is there something I should disable somewhere or is there another way of bootstrapping this?

**Comment by diml** [comment]
ocaml-compiler-libs is not part of core

**Comment by jaapb** [comment]
Do you mean it uses the compiler-libs package that comes with ocaml? (If you don't use opam, that gets installed as compiler-libs.common; Googling for ocaml-compiler-libs.common mostly returns ocaml-core, which would explain the confusion...)

**Comment by diml** [comment]
[ocaml-compiler-libs](https://github.com/janestreet/ocaml-compiler-libs) is simply a repackaging of `compiler-libs`, putting all the modules under a toplevel name. It's just to so that we can clearly identify what comes from the compiler-libs and what come from other libraries in our code. The compiler libraries expose all their modules at toplevel, which is a huge pain.

**Comment by jaapb** [comment]
Yup, I've found the package now. Weird that it doesn't show up on Google. Anyway, thanks for your help!
